Setup and mobile version skeleton
aeh1707/microverse-portfolio pull request #1
Opened 2022-04-21 20:23 UTC by aeh1707

A mobile version for a portfolio's header is set up in this feature branch.
Flexbox is used for layout.

2022-04-21 21:17 UTC, ShahierNashaat requested changes
Hi @aeh1707 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-21 21:17 UTC, ShahierNashaat commented on index.html
> +            <p class="logo">my logo</p>
- [ ] Please put the logo inside an `a` tag instead of `p` tag.

2022-04-21 21:17 UTC, ShahierNashaat commented on index.html
> +            <img class="burger" src="graphics/burger-menu.svg" alt="">
- [ ] Please put the hamburger button inside a `nav` tag.

2022-04-21 21:17 UTC, ShahierNashaat commented on index.html
> +        <div class="intro">
- [ ] Please end the `header` tag before `intro` class.
- [ ] Also instead of using `div` tag in the `intro` class use `section` tag.

2022-04-21 21:17 UTC, ShahierNashaat commented on index.html
> +                </h1>
- [ ] Kindly be noticed that the main title (e.g., "I'm Marianne ...") is a `h1` tag and the subtitle (if existing) uses a header tag `hx (examples: <h1>,<h2>,<h3>, etc...)` so you can but `I'm mariane` in an `h1` tag and `glad to see you!` in an `h2` tag.

2022-04-22 05:10 UTC, CollinsTatang requested changes
Hi @aeh1707, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 05:10 UTC, CollinsTatang commented on index.html
> +            </nav> -->
- [x] Kindly remove all commented code from your codebase to make it clean and maintainable.

2022-04-22 05:10 UTC, CollinsTatang commented on README.md
> +
- [ ] Kindly remove all commented code in your codebase to make it clean and maintainable.

2022-04-22 05:20 UTC, CollinsTatang approved these changes
# Approved 👏  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/55596970/158098566-50966056-ce3d-4c4b-aac3-cce7a7d107fb.png)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 05:22 UTC, merged